src/components/OutlinedButton.jsx, src/styles/GlobalStyle.jsx
=> 공통 컴포넌트 OutlinedButton 생성 완료

src/components/Input.jsx
=> 공통 컴포넌트 Input 완료

src/components/CustomSelect.jsx
=> 공통 컴포넌트 CustomSelect 완료

src/App.jsx, src/components/Navigation.jsx, src/styles/GlobalStyle.jsx
=> [공통 Component] 공통 nav 컴포넌트 생성

src/components/ui/button/PrimaryButton.jsx, src/components/ui/button/SecondaryButton.jsx, src/styles/GlobalStyle.jsx
- Primary&White Color GlobalStyle로 지정
- 파일 위치(Component/ui/Button) 변경
=> style : Primary&White Color GlobalStyle로 지정/파일 위치 변경

README.md
main 브랜치와 feature 브랜치의 README 디자인을 고정합니다.
=> docs: README 고정 디자인 반영

src/components/domain/post/PostBackground.jsx, src/constant/VariableSettings.jsx, src/services/GetRecipients.jsx
- [ x] 커밋 메시지 컨벤션에 맞게 작성했습니다.
#76  [공통 Component] 공통 card 배경 component 생성 
=> feature: 롤링 페이퍼 배경 선택 및 conflict 문제 해결

src/components/ui/badge/Badge.jsx
16
기존 Styled Component로 작업 돼 있던 단순 UI를 재사용 할 수 있도록 코드를 추가하였습니다.
=> [공통 컴포넌트] Badge 공통 컴포넌트의 재사용성을 높임

src/styles/GlobalStyle.jsx
가운데 영역 반응형 코드가 사라져 다시 추가하였습니다.
=> chore: 가운데 영역 반응형 코드가 사라져 다시 추가

src/components/ui/modal/Modal.jsx
=> [공통 컴포넌트]모달 ui 추가

src/components/ui/badge/Badge.jsx
=> chore: UI 디자인 수정

src/App.jsx, src/components/ui/modal/Modal.jsx
버튼 공통 컴포넌트가 작업 완료되어 기존에 작업 됐던 모달 내 컴포넌트를 교체하고, 모바일 버전의 UI가 깨지는 현상이 발생하여 부분 수정하였습니다.
=> chore: 공통 컴포넌트 Modal UI 수정

src/components/ui/nav/Navigation.jsx
=> chore: 네비게이션 배경색 누락으로 투명하게 출력되던 버그 수정

src/components/domain/list/Carousel.css, src/components/domain/list/CarouselSec1.jsx, src/components/domain/list/CarouselSec2.jsx, src/components/domain/list/List.module.css, src/components/domain/list/PostCard.jsx, src/components/ui/badge/Emoji.jsx, src/components/ui/nav/Navigation.jsx, src/constant/CarouselSettings.jsx, src/services/GetRecipients.jsx
#15
반응형 및 데이터 출력을 위한 PostCard.jsx 의 코드 수정이 있었습니다.
=> [롤링페이퍼 목록 페이지] 2차 UI (반응형) 구현 및 데이터 출력 완료

src/components/ui/nav/Navigation.jsx
네비게이션 로고 Link 추가 및 prop 관련 이슈 수정이 있었습니다.
=> fix: 네비게이션 로고 Link 추가 및 prop 관련 이슈 수정

src/components/domain/list/Carousel.css, src/components/domain/list/CarouselSec1.jsx, src/components/domain/list/CarouselSec2.jsx, src/components/domain/list/PostCard.jsx
=> chore: 불필요한 코드 삭제

package-lock.json, package.json, src/App.jsx, src/components/domain/list/CarouselSec1.jsx, src/components/domain/list/CarouselSec2.jsx, src/components/domain/post/MessageCard.jsx, src/components/ui/badge/Emoji.jsx, src/components/ui/button/RoundButton.jsx, src/pages/postID/PostId.css, src/pages/postID/PostId.jsx
1.리스트페이지 파라미터 값 받아와서 해당 데이터 출력
2.모바일에서 홈버튼 클릭 시 메인으로 이동
=> feat: 1.롤링페이퍼 페이지 - body 메세지 데이터 출력 2.홈버튼 클릭 시 메인이동

src/components/domain/list/CarouselSec1.jsx, src/components/domain/list/CarouselSec2.jsx
#130 
기본 limit 쿼리 스트링으로 인해 데이터가 8개만 출력되는 이슈를 수정하였습니다.
=> [롤링페이퍼 목록 페이지] offset으로 인해 데이터가 8개만 출력되는 이슈 수정

src/components/domain/list/CarouselSec1.jsx, src/constant/CarouselSettings.jsx
…라이드가 한 라인 뒤에서 시작 되는 원인불명의 이슈 수정
#133 
모바일 시 터치에 따라 Auto Slide가 멈추는 버그 수정 및 테스트코드 삭 제 후 반응형일 때 첫 렌더링 시 슬라이드가 한 라인 뒤에서 시작 되는 원인불명의 이슈 수정되었습니다.
=> fix: 모바일 관련 캐로셀 버그 수정

package-lock.json, package.json, src/components/ui/button/RoundButton.jsx, src/components/ui/loading/Loading.jsx, src/pages/post/CreatePost.jsx, src/pages/postID/PostId.css, src/pages/postID/PostId.jsx
=> [롤링페이퍼 페이지 - Body]무한 스크롤 기능 구현-v2

src/components/ui/modal/Modal.jsx, src/pages/post/message/MessageModal.jsx
=> feat: message 모달 [확인] 버튼 클릭 시 닫힘 기능 추가

src/components/domain/post/CreatePost.css, src/components/domain/post/PostBackground.jsx, src/pages/post/CreatePost.jsx
=> style: 모바일, 테플릿 미디어 쿼리 적용

src/components/domain/postId/postHead/PostHead.module.css
배경색이 누락되어 투명하게 보이던 UI적 버그 수정하였습니다.
=> chore: 배경색 누락 건 수정

src/components/ui/nav/Navigation.jsx, src/styles/GlobalStyle.jsx
1. 글로벌 스타일의 container의 가운데 정렬 코드가 누락되어 추가하였습니다.
2. 네비게이션의 '롤링페이퍼 만들기' 버튼의 {/post} 경로를 추가하였습니다.
=> fix: 글로벌 스타일 내 container 가운데 정렬 코드 추가 및 네비게이션 버튼 경로 추가

src/components/domain/list/CarouselSec1.jsx, src/components/domain/list/CarouselSec2.jsx, src/components/domain/list/List.module.css, src/components/domain/list/Skeleton.jsx, src/components/domain/list/Skeleton.module.css
#122 
데이터 출력 시(첫 렌더링) 빈 공간이 먼저 출력되어 로딩중임을 암시하는 스켈레톤 효과를 추가하였습니다.
=> [롤링페이퍼 목록 페이지] 데이터 불러올 때 스켈레톤 효과 추가

src/pages/postID/PostId.css, src/pages/postID/PostId.jsx
이전 작업물로 코드 수정이 진행됨으로 최신코드가 수정된 코드로 머지 된상태에서 최신코드와 
수정코드 재작업 진행
=> fix: postId 컴포넌트 코드 충돌로 인한 코드 재수정

package-lock.json, package.json, src/components/domain/postId/postHead/PostHead.module.css
#154 
z-index 값이 누락되어 Body 쪽 메세지 카드에 가려지는 이슈 해결 및 이모지 클릭 범위가 너무 넓어 최소한으로 줄여놓았습니다.
=> [롤링페이퍼 목록 페이지 - Head] z-index 누락으로 메세지 카드에 가려지는 이슈 해결 및 이모지 클릭 범위를 줄임

public/index.html, src/components/domain/postId/postHead/PostHead.jsx, src/components/domain/postId/postHead/SharedContainer.jsx
=> [롤링페이퍼 페이지 - Head] 카카오톡 공유하기 기능 구현

src/components/domain/postId/postHead/PostHead.module.css
position absolute로 인해 width 값이 잡히지 않는 문제를 해결하기 위해 디바이스 값 변경이 있었습니다.
=> fix: 반응형 코드에 따른 CSS 이슈가 발견되어 미디어쿼리 디바이스 값 수정

src/components/domain/postId/postHead/SharedContainer.jsx
카카오 공유하기 설명이 각 링크에 알맞지 않아 수정되었습니다.
=> chore: 카카오 공유하기 description 수정

src/components/ui/button/PrimaryButton.jsx, src/pages/postID/PostId.css, src/pages/postID/PostId.jsx
… 트랜지션효과) 수정
#158 
#163 
#169 
테스트 과정 중 오류 수정작업.
=> fix:1.데이터가 없을 때 대응 ui 적용 2.태블릿, 모바일 양역 여백 3.롤링페이퍼 삭제하기 버튼(크기, 폰트 두께, 트랜지션효과) 수정

src/components/ui/button/PrimaryButton.jsx, src/pages/postID/PostId.jsx
=> chore: 버튼 컴포넌트 수정

src/pages/postID/PostId.jsx
#175 #39 
1. 메세지들 등록하면 2개가 출력되는 문제 해결
2. 롤링페이퍼 삭제 기능 구현
=> fix: 1.메세지 등록하면 2개 출력 되는 문제 2.롤링페이퍼 삭제 기능

src/components/domain/postId/postHead/PostHead.module.css
=> chore: 네비게이션 위치 조정

src/components/domain/postId/postHead/PostHead.jsx, src/components/ui/nav/Navigation.jsx
롤링페이퍼 페이지 반응형에 맞게 동적 UI 효과를 주기 위해 props 속성을 부여 했습니다.
=> chore: 네비게이션 및 롤링페이퍼 페이지 헤드에 props 값 추가

src/pages/postID/PostId.jsx
=> style: 데이터 없을 때 삭제 버튼 적용

src/components/ui/modal/Modal.jsx, src/pages/post/message/MessageModal.jsx, src/pages/postID/PostId.css, src/pages/postID/PostId.jsx, src/services/DeleteMessage.jsx, src/services/GetMessages.jsx
=> 메시지 모달 처리 

src/components/domain/post/ProfileImageSelect.jsx, src/pages/post/message/PostMessage.jsx
#179 
- 기본이미지를 png가 아닌 api의 첫 번째 이미지로 설정
=> #179 기본 이미지 중복 출력 제거

src/components/ui/modal/Modal.jsx, src/pages/post/message/MessageModal.jsx
=> fix: #188, #189 이슈 처리

src/components/domain/post/ProfileImageSelect.jsx, src/components/ui/select/CustomSelect.jsx, src/pages/post/message/PostMessage.jsx
=> CustomSelect 값에 맞게 출력

package-lock.json, package.json, src/components/domain/post/MessageCard.jsx, src/pages/postID/PostId.css, src/pages/postID/PostId.jsx
- [] 새로운 기능 추가
#203 
1.메세지 페이지 헤더, 네비게이션 모바일 ui 수정
2.메세지 카드 내용 폰트 적용되게 수정
=> style: 모바일네비게이션 숨기기, 모바일 헤드 위치조정

src/App.jsx, src/components/domain/post/CreatePost.jsx, src/components/domain/post/MessageCard.jsx, src/context/BackgroundContext.jsx, src/pages/postID/PostId.css, src/pages/postID/PostId.jsx
1.메세지카드 페이지 선택에 따른 배경이미지, 배경 컬러 적용
2.배경이 이미지일 경우 투명도 백그라운드 적용
=> style: 1. 메세지카드 페이지 선택에 따른 배경이미지, 배경 컬러 적용 2.배경이 이미지일 경우 투명도 백그라운드 적용
